const classifier = {
  clothing: {
    outerwear: {
      dresses: [
        "dark green gown",
        "bathrobe",
        "white dress",
        "silk gown",
        "white bathrobe",
        "floral dress",
        "glittery dress",
        "bear costume",
        "Bunny costume",
        "black dress",
        "red dress",
        "maid dress",
        "cocktail dress",
        "purple dress",
        "china_dress",
        "undressing",
        "nightdress",
        "nightgown",
        "yellow dress",
        "robe",
        "Robe opened up",
        "cow costume",
        "torn dress",
        "dressed",
        "pink dress",
        "orange sundress",
        "school_uniform",
        "crossdressing",
        "police uniform",
        "gown",
        "dresses",
        "maid uniform",
        "blue dress",
        "wedding dress",
        "dress",
        "office dress",
        "black robe",
        "sundress",
        "in army uniform",
        "short red dress",
        "school uniform",
        "half dressed",
        "long dress",
        "open uniform",
        "Robe",
        "undress",
        "lift dress up",
        "uniform",
        "medieval dress",
        "Robes",
        "costume",
      ],
      bottoms: [
        "upskirt",
        "striped skirt",
        "black leggings",
        "denim shorts",
        "pencil skirt",
        "orange shorts",
        "shorts wedgie",
        "sweatpants",
        "plaid shorts",
        "red tight pants",
        "black pants",
        "no pants",
        "pants down",
        "short shorts",
        "brown pants",
        "brown skirt",
        "pink skirt",
        "out Underpants",
        "shorts",
        "skirt lift",
        "torn jeans",
        "unzipped pants",
        "mini skirt",
        "lifted skirt",
        "micro skirt",
        "underskirt",
        "miniskirt",
        "skirt_lift",
        "white skirt",
        "taut skirt",
        "black miniskirt",
        "booty shorts",
        "blueskirt",
        "shorts down",
        "tight jeans",
        "green shorts",
        "ripped pants",
        "blue skirt",
        "baggy pants",
        "plaid skirt",
        "black skirt",
        "short skirt",
        "white pants",
        "lifting skirt",
        "tight skirt",
        "Underpants",
        "red skirt",
        "no skirt",
        "jean hotpants",
        "leggings",
        "pleated_skirt",
        "hotpants",
        "skirt",
        "Pants",
        "slit skirt",
        "pants pull",
        "shortstack",
        "pleated shorts",
        "torn skirt",
        "mini skirt bra",
        "pleated skirt",
        "jean shorts",
        "lift skirt",
        "pants",
        "jeans",
      ],
      tops: [
        "sweater lift",
        "shirt torn off",
        "shirt up",
        "shirt in mouth",
        "jacket",
        "sweatshirt lift",
        "collared shirt",
        "lifting shirt",
        "croptop",
        "tight tank top",
        "tied shirt",
        "grey shirt",
        "shirtless",
        "black crop top",
        "shirt pull",
        "white t-shirt",
        "tanktop",
        "plaid shirt",
        "sweatshirt",
        "open shirt",
        "formal shirt",
        "brown jacket",
        "white tank top",
        "white shirt",
        "saliva on shirt",
        "plain t-shirt",
        "cropped jacket",
        "sweater",
        "shirt",
        "red sweater",
        "white_shirt",
        "open jacket",
        "tank top",
        "lifted t-shirt",
        "gray t-shirt",
        "pulling shirt",
        "blue jacket",
        "open_shirt",
        "pink crop top",
        "downblouse",
        "tshirt",
        "black jacket",
        "blouse",
        "white sweater",
        "shirt_lift",
        "blue shirt",
        "wet shirt",
        "hoodie",
        "green shirt",
        "shirt lifted up",
        "t-shirt",
        "pink tshirt",
        "pull shirt",
        "crop top",
        "shirt open",
        "yellow tank top",
        "black shirt",
        "shirt lift",
        "white crop top",
        "white tanktop",
      ],
    },
    legwear: {
      short: [
        "anklets",
        "knee-high socks",
        "gold anklets",
        "leg warmers",
        "socks",
        "baggy socks",
        "legwarmers",
        "white socks",
        "knee socks",
      ],
      specific: [
        "laced",
        "laces",
        "lace",
        "pearl necklace",
        "striped skirt",
        "lace bra",
        "gold necklace",
        "striped clothes",
        "garter belt",
        "golden neclace",
        "lace panties",
        "fishnet",
        "elf palace",
        "palace bedroom",
        "striped",
        "lace choker",
        "golden necklace",
        "in ice palace",
        "lace trim",
        "fishnets",
        "tight fishnets",
        "anchor necklace",
        "lace lingerie",
        "laced bodysuit",
        "neclace",
        "lace stockings",
        "egyptian palace",
        "black lace bra",
        "palace",
        "lacey",
        "striped bikini",
        "purple necklace",
        "glaceon",
        "fishnet sleeve",
        "fishnet gloves",
        "lace thong",
        "fishnet thighs",
        "lace tighhighs",
        "black fishnet",
        "heart necklace",
        "necklace",
        "white lace",
      ],
      full_length: [
        "torn thighhighs",
        "black leggings",
        "Stockings",
        "tights",
        "thighhighs",
        "white pantyhose",
        "pantyhose pull",
        "blue stockings",
        "pink stockings",
        "white stockings",
        "stockings",
        "torn pantyhose",
        "lace stockings",
        "leggings",
        "red stockings",
        "black pantyhose",
        "pantyhose",
        "red thighhighs",
        "black stockings",
        "gold stockings",
        "sexy stockings",
      ],
    },
    accessories: {
      hands: [
        "dangly earrings",
        "bracelets",
        "purple gloves",
        "big earrings",
        "frilled gloves",
        "latex gloves",
        "hop earrings",
        "white_gloves",
        "gloves",
        "cum on gloves",
        "earings",
        "white gloves",
        "elbow gloves",
        "long gloves",
        "saliva strings",
        "rings",
        "metal rings",
        "cum strings",
        "racing gloves",
        "nipple rings",
        "gold bracelets",
        "blue gloves",
        "strings",
        "earrings",
        "black gloves",
        "fishnet gloves",
        "hoop earrings",
        "black_gloves",
        "gold earings",
      ],
      neck: [
        "pearl necklace",
        "wet panties",
        "tied up",
        "pantieseyes",
        "sweetie",
        "cotton panties",
        "hands tied",
        "print panties",
        "lace panties",
        "panties on",
        "bdsm choker",
        "sailor_collar",
        "purple necklace",
        "tied hands",
        "aqua necktie",
        "blue collar",
        "hand on panties",
        "collars",
        "tie",
        "feet tied",
        "sailor collar",
        "heart necklace",
        "detached_collar",
        "thoty_katieXL",
        "ribbon choker",
        "highleg panties",
        "blue panties",
        "tied shirt",
        "choker",
        "white panties",
        "collared",
        "lace choker",
        "panties",
        "scarf",
        "cutie mark",
        "bell choker",
        "cutie",
        "twenties",
        "early twenties",
        "frilled panties",
        "black collar",
        "gold choker",
        "blue_bowtie",
        "legs tied",
        "panties visible",
        "thotty_katieX",
        "black tie",
        "fur collar",
        "necktie",
        "bowtie",
        "crownbraid tie",
        "tie clip",
        "collarbone",
        "collar",
        "black panties",
        "black choker",
        "hogtied",
        "gold collar",
        "hairtie",
        "red choker",
        "cuties",
        "pink panties",
        "impatient",
        "pink choker",
        "necklace",
        "gold necklace",
        "blue choker",
        "arms tied",
        "collared shirt",
        "detached collar",
        "sweetie belle",
        "tail tied",
        "panties aside",
        "golden necklace",
        "no panties",
        "panties down",
        "spiked collar",
        "hattiezazu",
        "low-tied",
        "green collar",
        "anchor necklace",
        "dog collar",
        "thotty_katieXL",
        "tiny panties",
        "linked collars",
        "red bowtie",
        "tied",
      ],
      head: [
        "wool hat",
        "hatsune",
        "crown",
        "capelet",
        "small maid hat",
        "black hat",
        "Captivating",
        "tiara",
        "white veil",
        "silver tiara",
        "tennis cap",
        "crownbraid tie",
        "beanie",
        "crownbraid",
        "golden tiara",
        "garrison cap",
        "gold crown",
        "anime screencap",
        "mikuhatsune",
        "capped",
        "crown braid",
        "hattiezazu",
        "hat",
        "capped sleeves",
        "military hat",
        "screencap",
        "miku hatsune",
        "veil",
        "that",
        "jester cap",
        "fur hat",
        "witch hat",
        "maid hat",
        "sports cap",
        "hatsune miku",
        "headband",
        "captured",
        "sailor hat",
        "phatassglas",
        "gold tiara",
        "cap",
        "bridal veil",
        "what",
        "landscape",
        "laurel crown",
        "cape",
      ],
      other: [
        "jewelry",
        "black belt",
        "circle glasses",
        "gold jewelry",
        "red sunglasses",
        "suspender belt",
        "beaded jewelry",
        "shaped jewelry",
        "sunglasses",
        "belts",
        "garter belt",
        "suspenders",
        "glasses",
        "belt",
        "opaque glasses",
        "round glasses",
      ],
    },
    underwear: {
      bottoms: [
        "wet panties",
        "pantieseyes",
        "low rise thong",
        "cotton panties",
        "print panties",
        "lace panties",
        "black thong",
        "highleg panties",
        "blue panties",
        "white panties",
        "panties aside",
        "panties on",
        "panties",
        "micro thong",
        "panties down",
        "no panties",
        "black panties",
        "frilled panties",
        "thong",
        "tiny panties",
        "crotchless",
        "thongs",
        "lace thong",
        "hand on panties",
        "showing thong",
        "pink panties",
        "panties visible",
      ],
      full: [
        "wet bikini",
        "black corset",
        "small BIKINI",
        "pink leotard",
        "white leotard",
        "bikini up",
        "mesh bodysuit",
        "teddy",
        "blue bodysuit",
        "torn bodysuit",
        "floral bikini",
        "green swimsuit",
        "white bikini",
        "maroon bodysuit",
        "white swimsuit",
        "swimsuit",
        "red corset",
        "sexy red bikini",
        "frilled bikini",
        "green bodysuit",
        "black_leotard",
        "small corset",
        "bikini pull",
        "one-piece",
        "black bodysuit",
        "latex bodysuit",
        "leotard_aside",
        "laced bodysuit",
        "BIKINI",
        "highleg leotard",
        "pink corset",
        "bikini",
        "Bikini",
        "striped bikini",
        "microbikini",
        "leotard",
        "teddy bear",
        "corset",
        "bikini top lift",
        "bodysuit",
        "mini bikini",
        "string bodysuit",
        "orange leotard",
        "tight swimsuit",
        "corset_piercing",
        "latex corset",
        "black bikini",
        "sling bikini",
        "micro bikini",
        "black leotard",
      ],
      tops: [
        "strong embrace",
        "bracelets",
        "brand new",
        "lace bra",
        "Brave",
        "small bra",
        "Brazilian girl",
        "vibrator",
        "crownbraid tie",
        "crownbraid",
        "pull wet bra",
        "frilled bra",
        "library",
        "bra",
        "gold bracelet",
        "Vibrant",
        "black lingerie",
        "bra lift",
        "Brazilian",
        "Brazil",
        "zebra",
        "cobra",
        "braids",
        "blue bra",
        "zebra dick",
        "Bra",
        "no bra",
        "lingerie",
        "zebra dicks",
        "crown braid",
        "Brazil jungle",
        "red bracers",
        "strapless",
        "bracers",
        "braless",
        "embrace",
        "beige bra",
        "sexy lingerie",
        "wet bra",
        "lace lingerie",
        "white bra",
        "gray sports bra",
        "open torn bra",
        "white lingerie",
        "loose bra",
        "braid petite",
        "Brandon Wolfel",
        "french braid",
        "black lace bra",
        "Brandon",
        "library stacks",
        "vibrant",
        "black bra",
        "embracing",
        "sombra",
        "vibrant colors",
        "braixenpxl",
        "king sombra",
        "braided hair",
        "undersized bra",
        "bikini top lift",
        "membrane_",
        "brand",
        "sports_bra",
        "gold bracelets",
        "braided",
        "bracelet",
        "braid",
        "mini skirt bra",
        "single braid",
        "brazilian",
        "pulled bra",
        "twin braids",
        "bracer",
      ],
    },
    footwear: {
      heels: [
        "high-heels",
        "high heels",
        "platform heels",
        "heels",
        "stiletto heels",
      ],
      shoes: [
        "shoes",
        "no shoes",
        "running shoes",
        "ballet shoes",
        "sandals",
        "white sneakers",
        "sneakers",
        "black sneakers",
        "strappy sandals",
      ],
      boots: [
        "brown boots",
        "white boots",
        "armored boots",
        "gothic boots",
        "knee boots",
        "black boots",
        "boots",
        "thigh boots",
      ],
    },
  },
  body_parts: {
    genitals: {
      male: [
        "large balls",
        "cock too big",
        "huge big cock",
        "hube balls",
        "balloons",
        "veiny penis",
        "chubby balls",
        "taking in penis",
        "huge long dick",
        "cock on cheek",
        "hyper balls",
        "penis exposed",
        "short penis",
        "hyper penis",
        "yellow_balls",
        "licking penis",
        "very dark dick",
        "magicpenis",
        "hairy penis",
        "smooth penis",
        "erect cock",
        "large dicks",
        "tentacle cocks",
        "thick cock",
        "flaccid penis",
        "penis on ass",
        "focus on penis",
        "ball sucking",
        "2dicks1mouth",
        "dick in anus",
        "big penis",
        "penis erection",
        "dick out",
        "licking dick",
        "penis around",
        "huge balls",
        "penis in mouth",
        "cock licking",
        "glossy penis",
        "holding penis",
        "penis in pussy",
        "curved penis",
        "gigantic penis",
        "knoted penises",
        "penises around",
        "bouncing penis",
        "dick",
        "small balls",
        "small testicles",
        "admiring cock",
        "thick penis",
        "futa cock",
        "penis",
        "hyper testicles",
        "multiple cocks",
        "erect penis",
        "dragon dick",
        "large dick",
        "tongue on penis",
        "whole cock",
        "gigantic balls",
        "veiny_penis",
        "tiny dick",
        "dick on face",
        "big balls",
        "horse cock",
        "balls deep",
        "cocktail dress",
        "big_penis",
        "big black cock",
        "ball gag",
        "dark penis",
        "shaft",
        "licking cock",
        "hyperpenis",
        "dog penis",
        "big cock",
        "white penis",
        "impaled by cock",
        "blue_penis",
        "penis over ass",
        "penis awe",
        "horsecock",
        "huge testicles",
        "huge fat cock",
        "huge penis",
        "green penis",
        "throbbing cock",
        "red ball gag",
        "cock exposed",
        "balls on nose",
        "dick cumming",
        "small penises",
        "dick in pussy",
        "horse penis",
        "2penises",
        "1penis",
        "dicks",
        "tiny penis",
        "cute penis",
        "ballerina",
        "many penises",
        "penis workship",
        "long penis",
        "stroking penis",
        "massive cock",
        "50 cm wide cock",
        "grabbing penis",
        "ballet",
        "licking balls",
        "tiny cock",
        "veiny cocks",
        "cock_pov",
        "teasing cock",
        "cum on balls",
        "ball",
        "cock won't fit",
        "face on balls",
        "penis close-up",
        "penish",
        "two large cocks",
        "cocky",
        "horsecocks",
        "Huge penis",
        "tapered penis",
        "stroking cock",
        "shiny penis",
        "huge cock",
        "huge dick",
        "cock worship",
        "holding balls",
        "cock slap",
        "black cock",
        "ballet shoes",
        "veiny cock",
        "detailed cock",
        "Horse dick",
        "penis in vagina",
        "balls on face",
        "baseball",
        "heavy balls",
        "penis on",
        "admiring a cock",
        "large penis",
        "huge dicks",
        "no testicles",
        "penis on belly",
        "big green dick",
        "giant penis",
        "big testicles",
        "sucking balls",
        "visible balls",
        "testicles",
        "massive penis",
        "cockshock",
        "penises",
        "man cock",
        "humanoid_penis",
        "penis Angle",
        "huge cocks",
        "chubby penis",
        "detailed balls",
        "equine penis",
        "big horse penis",
        "horse dick",
        "detailed penis",
        "oiled penis",
        "balls",
        "hand on cock",
        "pink_penis",
        "penis grab",
        "cock in ass",
        "big veiny cock",
        "big dick",
        "cocktail",
        "hanging penis",
        "cum on penis",
        "big veiny dick",
        "cock",
        "cock on face",
        "penis worship",
        "zebra dick",
        "swollen balls",
        "veiny dick",
        "zebra dicks",
        "huge black cock",
        "black balls",
        "small penis",
        "cocks",
        "penis on face",
        "veiny balls",
        "large penises",
        "wet penis",
        "cocked eyebrow",
        "penis cumming",
        "penis in face",
        "white_balls",
        "futa penis",
        "small cock",
        "testicle",
        "large cocks",
        "cocked",
        "cock tease",
        "black penis",
        "holing_penis",
        "kissing penis",
        "thick_penis",
        "cock in mouth",
        "sucking cock",
        "cock blush",
        "basketball",
        "hairy balls",
        "cock in pussy",
        "thick dick",
        "large testicles",
        "penisoveroneeye",
        "huge hairy dick",
        "hard cock",
      ],
      female: [
        "innie pussy",
        "exposed pussy",
        "labia",
        "pink pussy",
        "perfect pussy",
        "focus on vagina",
        "vaginal",
        "hands on pussy",
        "pussy showing",
        "pussy lips",
        "godpussy1",
        "very wet pussy",
        "naked vagina",
        "cum in pussy",
        "pussy_juice",
        "hand on pussy",
        "penis in pussy",
        "vaginal sex",
        "juicy pussy",
        "saggy labia",
        "wet pussy",
        "swollen pussy",
        "clitoral hood",
        "dripping pussy",
        "camel toe",
        "semen in vagina",
        "tight pussy",
        "nice pussy",
        "show pussy",
        "showing pussy",
        "pussy focus",
        "after vaginal",
        "hairy pussy",
        "vulva",
        "pussy peak",
        "wet pussy lips",
        "dick in pussy",
        "detailed pussy",
        "labia majora",
        "vaginalound",
        "pussy slip",
        "finger in pussy",
        "licking pussy",
        "flashing pussy",
        "big clit",
        "cute vagina",
        "cameltoe",
        "realistic pussy",
        "revealing pussy",
        "show wet pussy",
        "hairless pussy",
        "touching pussy",
        "hand in pussy",
        "sideways vagina",
        "fat pussy",
        "pussy exposed",
        "clitoral",
        "gaping pussy",
        "pussy sliding",
        "cum on pussy",
        "display pussy",
        "clit",
        "penis in vagina",
        "exposed_pussy",
        "pussy covered",
        "dildo in pussy",
        "exposing pussy",
        "clitoris",
        "pussy close-up",
        "legs up vaginal",
        "defined pussy",
        "cute pussy",
        "vagina focus",
        "spread pussy",
        "dripping vagina",
        "pussy peek",
        "cervix",
        "groping pussy",
        "rubbing vagina",
        "hairy vagina",
        "pussy",
        "beautiful pussy",
        "stretched pussy",
        "fingering pussy",
        "shiny pussy",
        "vagina",
        "double_vaginal",
        "pussy spread",
        "slave pussy",
        "pussy torture",
        "innie",
        "shaved pussy",
        "puffy pussy",
        "pussy piercing",
        "spreading pussy",
        "cock in pussy",
        "pussy visible",
        "pussy juice",
      ],
      anal: [
        "spread anus",
        "anus hair",
        "anal fisting",
        "anal sex",
        "anala",
        "anal penetratio",
        "thumb in anus",
        "tight pink anus",
        "cum in anus",
        "spreading anus",
        "asshole in view",
        "spit on anus",
        "anal cum",
        "after anal",
        "anal",
        "small anal gape",
        "anus spread",
        "dick in anus",
        "puffy anus",
        "perfect asshole",
        "focus anus",
        "exposed anus",
        "leaking asshole",
        "anal fingering",
        "anal_beads",
        "deep anal",
        "anal creampie",
        "asshole",
        "finger in anus",
        "hint of anus",
        "anal fuck",
        "anus",
        "butthole",
        "hairy anus",
        "gaping anus",
        "presenting anus",
      ],
    },
    face: {
      eyes: [
        "heart pupils",
        "half-open eyes",
        "focus on eyes",
        "Blue eyes",
        "pantieseyes",
        "sultry eyes",
        "bedroom eyes",
        "purple eyes",
        "pupil",
        "eyes wide open",
        "big round eyes",
        "light blue eyes",
        "eyebrow",
        "sharp eyes",
        "amber eyes",
        "deep pink eyes",
        "glowing_eyes",
        "blue eyes",
        "robot eyes",
        "lustful eyes",
        "irish Girl",
        "wide eyes",
        "Half open eyes",
        "tired eyes",
        "eyebrows",
        "dark eyeliner",
        "dark blue eyes",
        "thick_eyebrows",
        "long eyelashes",
        "yellow eyes",
        "eyes glowing",
        "eye contact",
        "glowing eyes",
        "round eyes",
        "thick eyebrows",
        "red_eyes  soles",
        "seducive eyes",
        "EyeDetail",
        "beautiful_eyes",
        "dashed_eyes",
        "amazing eyes",
        "narrowed eyes",
        "rolled eyes",
        "wide eyebrow",
        "purple_eyes",
        "expressive eyes",
        "fisheye view",
        "brown_eyes",
        "black eyes",
        "dark brown eyes",
        "black_eyebrows",
        "from eyes view",
        "wide open eyes",
        "large eyes",
        "mechanical eye",
        "dreamy eyes",
        "slit_pupils",
        "orange eyes",
        "dark pupils",
        "hot cat eyes",
        "dark grey eyes",
        "asymmetry eyes",
        "hearts in eyes",
        "half-closed eye",
        "black eyeshadow",
        "iris",
        "blank eyes",
        "raised eyebrows",
        "uneven eyes",
        "pupils",
        "artificial eye",
        "eyerbrows",
        "detailed irises",
        "eye catching",
        "hazel eyes",
        "gray eyes",
        "closed  eyes",
        "green eyes",
        "depraved eyes",
        "eye rolling",
        "pink eyes",
        "orange_eyes",
        "perfecteyes",
        "blue_eyes",
        "eyes brown",
        "green-eyes",
        "beautiful eyes",
        "dark eyeshadow",
        "adorable eyes",
        "scar across eye",
        "spiral eyes",
        "thick eyerbrows",
        "eyewear",
        "hypnotic eyes",
        "clear eyes",
        "correct eyes",
        "iceblue eyes",
        "Big blue eyes",
        "kaa eyes",
        "seductive eyes",
        "big brown eyes",
        "eyes up",
        "empty eyes",
        "close eyes",
        "hearts in pupil",
        "white eyes",
        "asian eyes",
        "Red eyes",
        "eyes open",
        "eyes closed",
        "rolling eyes",
        "eyeliner",
        "very big eyes",
        "large blue eyes",
        "glowing-eyes",
        "realistic eyes",
        "squint eyes",
        "yellow_eyes",
        "eyeshadow",
        "fisheye lens",
        "big eyes",
        "bushy eyebrow",
        "aqua eyes",
        "Eyes half open",
        "big green eyes",
        "eye lighting",
        "nice eyes",
        "silver eyes",
        "runny eyeliner",
        "eyes",
        "black eyeliner",
        "round eyewear",
        "Eyes",
        "eye",
        "eyes_closed",
        "fisheye",
        "wide eyed",
        "Black eyes",
        "red_eyes",
        "eye catchlights",
        "bright eyes",
        "irish",
        "lidded eyes",
        "eyeless",
        "eyed",
        "detailed eyes",
        "raised eyebrow",
        "red eyes",
        "eyes crossed",
        "brown eyes",
        "eyewear on head",
        "penisoveroneeye",
        "irises",
        "green_eyes",
        "eyebrow cut",
        "glowing_eye",
        "brunette eyes",
        "open eyes",
        "cocked eyebrow",
        "eyes turned up",
        "green eye color",
        "grey eyes",
        "eyelashes",
        "amber_eyes",
        "eye color green",
        "dilated pupils",
        "dark eyes",
        "wide-eyed",
        "crossed eyes",
        "eyes rolling",
        "perfect eyes",
        "closed eyes",
        "yellow eye",
        "eyes shut",
        "turquoise eyes",
        "mole under eye",
        "gold eyes",
      ],
      mouth: [
        "Sexy mouth",
        "lips on nipple",
        "mouths",
        "teeths",
        "tongue_out",
        "covered mouth",
        "tongues",
        "purple lips",
        "full lips",
        "areola slip",
        "pulling lips",
        "clenched teeth",
        "mouth",
        "cuminmouthXL",
        "black teeth",
        "huge lips",
        "tongue out",
        "biting lip",
        "pussy lips",
        "perfect teeth",
        "2dicks1mouth",
        "wet lips",
        "black lipstick",
        "very full lips",
        "very thick lips",
        "mouth pull",
        "Tongue",
        "long tongue",
        "penis in mouth",
        "spit on mouth",
        "puffy lips",
        "grit the teeth",
        "pink lipstick",
        "nip slip",
        "mouth drooling",
        "big lips",
        "beautiful mouth",
        "lips parted",
        "big bimbo lips",
        "sharp teeth",
        "hairclips",
        "open_mouth",
        "tongue on penis",
        "perfect teeths",
        "thick tongue",
        "injected lips",
        "thin lips",
        "bottle in mouth",
        "wet mouth",
        "pink_tongue",
        "black lips",
        "plump lips",
        "lips",
        "open lips",
        "focus on tongue",
        "wet pussy lips",
        "bimbo lips",
        "huge bimbo lips",
        "slippery nipple",
        "pussy slip",
        "teeth",
        "licking lips",
        "large boob slip",
        "sharp_teeth",
        "cum on mouth",
        "glossy lips",
        "clips",
        "cum on tongue",
        "full pouty lips",
        "purple lipstick",
        "closed_mouth",
        "biting own lip",
        "flipflops",
        "shirt in mouth",
        "nipslip",
        "slipping",
        "lip",
        "clip",
        "full pink lips",
        "tie clip",
        "lip bite",
        "thick lips",
        "mouth taped",
        "thick full lips",
        "red lip gloss",
        "thicc lips",
        "mouth covered",
        "wide open mouth",
        "blue lipstick",
        "slippery",
        "finger on lips",
        "shiny lips",
        "perfect lips",
        "tape_on_mouth",
        "hair clips",
        "megumi katou",
        "hairclip",
        "open mouth",
        "beautiful lips",
        "mouth open",
        "shiny tongue",
        "closed mouth",
        "dark lipstick",
        "detailed lips",
        "luscious lips",
        "gritting teeth",
        "tongue drop",
        "clenching teeth",
        "Biting your lip",
        "mouth closed",
        "red lipstick",
        "hand in mouth",
        "tongue teasing",
        "hair_clip",
        "tongue",
        "pink tongue",
        "mouth relaxed",
        "wavy mouth",
        "parted lips",
        "areolae slip",
        "clenched_teeth",
        "megumi",
        "lip biting",
        "cum in mouth",
        "cock in mouth",
        "teeth tight",
        "slip",
        "hand over mouth",
        "nipple slip",
        "lipstick",
        "red lips",
        "gaping mouth",
      ],
      jaw: [
        "strong jaw",
        "cum on chin",
        "streching ass",
        "reaching",
        "touching pussy",
        "china_dress",
        "clenching teeth",
        "double chin",
        "group watching",
        "arching back",
        "bewitching",
        "reaching back",
        "chin",
        "eye catching",
        "touching body",
        "catching",
        "jawline",
        "milking machine",
        "machine",
        "streching",
        "crouching",
        "touching",
        "reaching_out",
        "jaw",
        "watching",
        "outstretching",
        "strong jawline",
        "sharp jawline",
        "pinching",
        "twitching",
        "arching",
        "clenching",
      ],
      skin: [
        "freckle",
        "molest",
        "sexy mole",
        "freckled breast",
        "mole",
        "mole on breast",
        "freckled",
        "freckless",
        "heavy freckles",
        "freckles",
        "Freckles",
        "light freckles",
        "mole under eye",
        "facial freckles",
        "molesting",
        "freckled face",
      ],
      nose: [
        "nostrils",
        "large nose",
        "balls on nose",
        "perfect nose",
        "bubble in nose",
        "nose",
        "nose blush",
        "nose ring",
        "cum in nose",
        "cute nose",
        "nose piercings",
        "cum out of nose",
        "small nose",
        "thin nose",
        "high nose",
      ],
      cheeks: [
        "cock on cheek",
        "cheeks",
        "cheekbones",
        "spread cheeks",
        "dimples",
        "rosy cheeks",
        "cheek press",
        "high cheekbones",
        "cheek bulge",
        "cheek",
        "cheekless",
      ],
    },
    limbs: {
      arms: [
        "large biceps",
        "arm up",
        "arms",
        "arms spread",
        "after armpits",
        "arms_up",
        "veiny arms",
        "spread armpits",
        "armpit fetish",
        "thick arms",
        "soft warm light",
        "arms tattooed",
        "arms up",
        "elbows",
        "legwarmers",
        "cellulite arms",
        "arm",
        "in army uniform",
        "warm smile",
        "hairy arms",
        "arm tattoos",
        "elbow",
        "armlet",
        "warmers",
        "warm light",
        "ARM",
        "forearm",
        "armored boots",
        "cum in armpits",
        "armring",
        "blue doll arms",
        "tattooed arms",
        "armpits",
        "Farm background",
        "shaved armpits",
        "armored",
        "farm",
        "arms behind bck",
        "bare arms",
        "wrist",
        "army",
        "warm",
        "mechanical arm",
        "selfie arms",
        "warm lighting",
        "arm support",
        "hairy armpits",
        "armchair",
        "arm over head",
        "armpit hair",
        "arms on breasts",
        "on elbows",
        "leg warmers",
        "small arms",
        "armpit",
        "arms tied",
        "four arms",
        "Warm",
        "arm raised",
        "extra arms",
        "gamesWarm",
        "fat arm folds",
        "wrists",
        "wrist cuffs",
        "gold armor",
        "armband",
        "elbow gloves",
        "clean armpit",
        "ARM UP",
        "fat obese arms",
        "wrists bound",
        "biceps",
        "armour",
        "arm pull",
        "bound arms",
        "Farm",
        "armlets",
        "armor",
      ],
      legs: [
        "fit legs",
        "black leggings",
        "thighhighs",
        "kneeling facial",
        "college",
        "blushing skin",
        "thighhigh",
        "animal legs",
        "shining",
        "thighjob",
        "closed legs",
        "amazing thighs",
        "legs spread",
        "spread legs",
        "elegant",
        "girl kneeling",
        "large thighs",
        "legwear",
        "legs spreag",
        "holding legs",
        "sexy legs",
        "thigh gap",
        "legwarmers",
        "leg",
        "highleg leotard",
        "one leg raised",
        "knees",
        "long slim legs",
        "wide thights",
        "shiny_skin",
        "shiny skin",
        "on knees",
        "skinny thighs",
        "white legwear",
        "four legs",
        "slim legs",
        "knee-high socks",
        "bandaged leg",
        "muscular thighs",
        "thin legs",
        "establishing",
        "cum on legs",
        "thin thighs",
        "highleg panties",
        "Legoshi",
        "thighs gap",
        "legs around man",
        "closed_legs",
        "sun shine",
        "legs raised",
        "legs apart",
        "kneeling",
        "genshin_impact",
        "thigh strap",
        "shine",
        "cum on thigh",
        "heavy blushing",
        "legged",
        "on her knees",
        "1leg up",
        "thights",
        "leg grab",
        "astonishing",
        "knee-high",
        "shiny metal",
        "highleg",
        "one knee up",
        "legs in v",
        "thick thighs",
        "gushing",
        "thin knees",
        "thicc thighs",
        "legs in the air",
        "legs tied",
        "pushing",
        "flashing pussy",
        "legs together",
        "kneeling female",
        "toned thighs",
        "kneepits",
        "KNEE",
        "shiny hair",
        "college student",
        "knee up",
        "torn thighhighs",
        "1leg down",
        "slender legs",
        "thigh_gap",
        "legs wide",
        "shiny penis",
        "legends",
        "1 leg up",
        "blushing smug",
        "plump thighs",
        "buried knees",
        "blushing",
        "a four legged",
        "Thighhigh",
        "elegant face",
        "knee boots",
        "crossed legs",
        "knee",
        "long legs",
        "bound legs",
        "spreading legs",
        "both legs up",
        "legs open",
        "fat knees",
        "sexy thighs",
        "trained thighs",
        "light blushing",
        "flashing",
        "muscle legs",
        "legs in air",
        "shiny lips",
        "legs up vaginal",
        "small legs",
        "college girl",
        "knees up",
        "Thick thighs",
        "leg_muscles",
        "thick legs",
        "legs",
        "hairy legs",
        "open legs",
        "leg warmers",
        "knee-highs",
        "thigh holster",
        "short legs",
        "Thigh",
        "leg up",
        "skin blushing",
        "thigh focus",
        "black legwear",
        "thigh",
        "tentacle legs",
        "kneeling slut",
        "shiny tongue",
        "thigh close up",
        "male legs",
        "1leg",
        "knees apart",
        "shiny clothes",
        "thigh highs",
        "thick_thighs",
        "on the knees",
        "legs up",
        "shiny pussy",
        "shiny",
        "Elegant",
        "perfect legs",
        "one leg up",
        "knee socks",
        "thighs",
        "hands on legs",
        "sunshine",
        "leggings",
        "big thighs",
        "1 girl leg up",
        "girl blushing",
        "fishnet thighs",
        "red thighhighs",
        "cuffs on legs",
        "skinny legs",
        "leg lift",
        "thigh-high",
        "dripping thigh",
        "thigh boots",
      ],
      hands: [
        "hands raised",
        "hand on face",
        "cum on hand",
        "hands",
        "hands tied",
        "perfect hands",
        "good_hands",
        "detailed hands",
        "FINGERING",
        "hands on pussy",
        "good fingers",
        "Perfect Hands",
        "one-handed",
        "ghost_hand",
        "handgun",
        "hand focus",
        "fingerfuck",
        "hand on pussy",
        "5_fingers",
        "five fingers",
        "palm",
        "pov hand",
        "negative_hand",
        "tied hands",
        "5fingers",
        "big hands",
        "Hand",
        "two-handed",
        "hand on panties",
        "Monster hands",
        "small hands",
        "hands down",
        "hand on own ass",
        "sucking finger",
        "v fingers",
        "Panam Palmer",
        "hand job",
        "hand fan",
        "hands on waist",
        "correct hands",
        "finger",
        "handcuffs",
        "perfect hand",
        "handsjob",
        "detailed hand",
        "finger in pussy",
        "hand on breast",
        "fingerless",
        "hand on head",
        "fingers",
        "pov hands",
        "hand in hair",
        "hand in pussy",
        "handsome",
        "hands own ass",
        "double handjob",
        "hand",
        "hands on ass",
        "Palmer",
        "Hands",
        "hand in ass",
        "love handles",
        "4 fingers",
        "anal fingering",
        "palm tree",
        "man hands pov",
        "finger in anus",
        "handjob behind",
        "finger on lips",
        "bandaged hand",
        "hands on table",
        "Hands down",
        "handsome man",
        "hands_on_wall",
        "fingers in ass",
        "fingering",
        "hand on cock",
        "POV_handjob",
        "fingernails",
        "perfect Hands",
        "left hand",
        "hands bound",
        "fingering pussy",
        "hands up",
        "hand in mouth",
        "hands on hips",
        "giving_handjob",
        "V hand sign",
        "handjob",
        "handles",
        "hands on legs",
        "hand_on_wall",
        "hand over mouth",
        "bound hands",
        "5finger",
        "slender hands",
      ],
      feet: [
        "camel toe",
        "camisole",
        "high heels",
        "cameltoe",
        "foot",
        "heels",
        "bound ankles",
        "footage",
        "steamy feet",
        "women bare feet",
        "feet focus",
        "feets",
        "perfect feet",
        "foot focus",
        "5 toes",
        "licking feet",
        "footjob",
        "black high heel",
        "paw feet",
        "gold anklets",
        "nice feet",
        "platform heels",
        "tiptoe",
        "perfect feets",
        "slim ankles",
        "monster feet",
        "hooves feet",
        "ankle",
        "thin ankles",
        "long toes",
        "black footwear",
        "4toes",
        "bodycam footage",
        "beautiful feet",
        "sole",
        "on tiptoe",
        "barefoot",
        "soles",
        "high-heels",
        "showing feet",
        "five toes",
        "tippy toes",
        "Feet",
        "feet",
        "gold footwear",
        "toes",
        "soles focus",
        "high heel",
        "thin ankle",
        "footwear",
        "cum_on_feet",
        "anklets",
        "small feet",
        "5toes",
        "toe",
        "normal feet",
        "red_eyes  soles",
        "one foot up",
        "two-footed",
        "stiletto heels",
        "feet on head",
        "ankles",
        "feet tied",
        "feet apart",
        "heel",
        "bare feet",
      ],
    },
    breasts: {
      features: [
        "nipples visible",
        "lips on nipple",
        "nipple peak",
        "cleavage cutout",
        "big areola",
        "nipple ring",
        "tiny nipples",
        "bihugeg nipples",
        "blue nipples",
        "perky nipples",
        "huge nipples 1",
        "big areolas",
        "boob areola",
        "thick nipples",
        "nipples torture",
        "nipple sticker",
        "defined nipples",
        "areola slip",
        "nipple-ring",
        "one nipple out",
        "licking nipple",
        "pink nipples",
        "nipple sucking",
        "Hard nipple",
        "pierced nipples",
        "big nipples",
        "nipple tweak",
        "nipple exposed",
        "wide areola",
        "pointy nipples",
        "hard nipples",
        "shaped nipples",
        "huge nipples",
        "erect nipples 1",
        "deep cleavage",
        "nipple piercing",
        "nipple peek",
        "nipple bulge",
        "whore cleavage",
        "swollen nipple",
        "areolae slip",
        "slippery nipple",
        "molded nipples",
        "cleavage",
        "nipples showing",
        "erect nipples",
        "areola",
        "large areolae",
        "light areolae",
        "large areola",
        "puffy nipple",
        "nipples out",
        "erected nipples",
        "nipple",
        "swollen nipples",
        "wide areolae",
        "sucking nipple",
        "areolas",
        "nipple rings",
        "puffy nipples",
        "pink_nipples",
        "errect nipples",
        "covered nipples",
        "perfect nipples",
        "show nipple",
        "nipple slip",
        "nipples",
        "areolae",
        "detail areola",
        "big areolae",
        "puffy areolas",
      ],
      size: [
        "flatchest",
        "small tits",
        "small chest",
        "big breast",
        "perky big tits",
        "huge breasts",
        "big breasts",
        "huge breast",
        "large breasts",
        "small breasts",
        "big boobs",
        "medium  breasts",
        "Huge Breasts",
        "huge boobs",
        "large breast",
        "big tits",
        "large boob slip",
        "small breast",
        "medium breasts",
        "medium tits",
        "medium chest",
        "round big tits",
        "medium boobs",
        "flat chest",
        "medium breast",
      ],
      shape: [
        "round breasts",
        "round tits",
        "perky breasts",
        "tiny perky tits",
        "perky boobs",
        "big perky boobs",
        "perky breast",
        "round boobs",
        "perky tits",
        "firm breasts",
        "saggy breasts",
        "saggy boobs",
        "saggy breast",
      ],
    },
    torso: {
      chest: [
        "massive breasts",
        "spectating",
        "breast grab",
        "underboob",
        "sideboob",
        "breast_press",
        "plump chest",
        "breast lift",
        "licking breast",
        "round breasts",
        "cum on boobs",
        "huge breasts",
        "round chest",
        "interspecies",
        "pecs jiggles",
        "sagging breasts",
        "fake boobs",
        "one breast out",
        "medium  breasts",
        "exposed pecs",
        "deep cleavage",
        "breasts too big",
        "grabbing boobs",
        "whore cleavage",
        "grabbing breast",
        "torpedo breasts",
        "huge boobs",
        "breasts exposed",
        "Pecs",
        "celicon breasts",
        "giant boobs",
        "breast",
        "pec grab",
        "medium chest",
        "firm breasts",
        "perfect breast",
        "breastsucking",
        "bouncing breast",
        "oiled breasts",
        "chest",
        "breast bondage",
        "mole on breast",
        "naked breasts",
        "side breast",
        "flatchest",
        "squeezing pecs",
        "Grab breast",
        "exposed breast",
        "busty chest",
        "exposed breasts",
        "pointy breasts",
        "large pectorals",
        "breasts",
        "big breasts",
        "chest out",
        "breasts grab",
        "focus on boobs",
        "small breasts",
        "breast rest",
        "boob grab",
        "squeeze breast",
        "Huge Breasts",
        "boob window",
        "side breasts",
        "backboob",
        "spectacular",
        "awesome breasts",
        "side boob",
        "low perspective",
        "hand on breast",
        "bare chest",
        "large boob slip",
        "small breast",
        "hold boobs",
        "medium breasts",
        "round boobs",
        "small_breasts",
        "breasts out",
        "hairy chest",
        "breastmilk",
        "boob",
        "Breast",
        "chest up",
        "pectorals",
        "breast squeeze",
        "big perky boobs",
        "hyper pecs",
        "breast_grab",
        "breast milk",
        "hugging breasts",
        "breasts squeeze",
        "small chest",
        "big breast",
        "focus on breast",
        "breasts visible",
        "pec sucking",
        "full breasts",
        "show breast",
        "breast tattoos",
        "chest hair",
        "pecs",
        "huge breast",
        "Breasts",
        "cum on breasts",
        "breast focus",
        "boob squeeze",
        "wet breasts",
        "breast implants",
        "big boobs",
        "perky breasts",
        "pec squeeze",
        "pec",
        "nice pecs",
        "jumpy boobs",
        "pec grabbing",
        "massive breast",
        "breasts apart",
        "chest harness",
        "large breast",
        "saggy boobs",
        "massive boobs",
        "petite breasts",
        "no boobs",
        "flat chest",
        "speculum",
        "soft breasts",
        "sucking breasts",
        "Oily breasts",
        "medium boobs",
        "arms on breasts",
        "breast feeding",
        "face in breasts",
        "medium breast",
        "cleavage cutout",
        "holding breasts",
        "giant breasts",
        "breasts on head",
        "perky breast",
        "perspective",
        "medium_breasts",
        "spit on chest",
        "boob areola",
        "breastfeeding",
        "saggy breast",
        "breast sucking",
        "freckled breast",
        "breastless",
        "boobs",
        "breasts shaking",
        "BREAST",
        "chest fluff",
        "gigantic breast",
        "perfect breasts",
        "Squish breast",
        "Spectacular",
        "large breasts",
        "boobjob",
        "breastfeed",
        "hanging breasts",
        "boob focus",
        "male breasts",
        "respectable",
        "Plump Pecs",
        "breast smother",
        "big pecs",
        "breast fondle",
        "long breast",
        "large pecs",
        "breast press",
        "bubble boobs",
        "cleavage",
        "breasts closeup",
        "grab breasts",
        "saggy breasts",
        "cum on chest",
        "sweaty breasts",
        "breast cutout",
        "breasts1",
        "perky boobs",
        "large_breasts",
        "groping breast",
        "boys spectating",
        "under boob",
        "natural breasts",
        "boobs closeup",
        "chestnut",
      ],
      abdomen: [
        "absurd details",
        "broad and abs",
        "Grabbing",
        "babe",
        "navel hair",
        "breast grab",
        "rabbit tail",
        "labia",
        "pot belly",
        "adorable girl",
        "abstract",
        "grabbing tail",
        "rabbit girl",
        "belly grab",
        "collaborative",
        "grabbing head",
        "arabian harem",
        "bare midriff",
        "hips grab",
        "tight abs",
        "grabbing sheets",
        "grabs",
        "throat grab",
        "grab mans head",
        "grabbing boobs",
        "big belly",
        "grabbing breast",
        "saggy labia",
        "sagging_belly",
        "torso grab",
        "adorable",
        "grabbing hair",
        "pec grab",
        "midriff",
        "round_belly",
        "cum on belly",
        "fabrics",
        "big navel",
        "establishing",
        "navel piercing",
        "head grab",
        "Grab breast",
        "Belly",
        "abdominal",
        "covered navel",
        "grabbing",
        "from_above",
        "abdomen",
        "breasts grab",
        "abs",
        "aberration",
        "cum on stomach",
        "leg grab",
        "stomach",
        "absurd",
        "labcoat",
        "jessica rabbit",
        "grab",
        "1 cute adorable",
        "boob grab",
        "fit belly",
        "labia majora",
        "grabbing dildo",
        "absurd res",
        "GRABBING",
        "adorable eyes",
        "adorable face",
        "grabbing penis",
        "flat tummy",
        "uncomfortable",
        "cables",
        "round navel",
        "bare navel",
        "breast_grab",
        "cabin",
        "skinny abdomen",
        "grabbing ass",
        "deepgrab",
        "noticeable",
        "grab butt",
        "belly overhang",
        "belly",
        "swamp cabin",
        "stomach bulge",
        "hair grab",
        "grabbed hair",
        "fat belly",
        "Jabstyle",
        "penis on belly",
        "bent over table",
        "pec grabbing",
        "flat stomach",
        "tits grab",
        "Sexy babe",
        "arabian clothes",
        "table",
        "ass grab",
        "grabbing hips",
        "Table",
        "Sex on Table",
        "laboratory",
        "rabbit ears",
        "hands on table",
        "belly dancer",
        "rabbit",
        "stability",
        "fabric",
        "ass grabbing",
        "Abuse",
        "penis grab",
        "Unforgettable",
        "sky above",
        "adorable woman",
        "absurd quality",
        "absurdly",
        "above",
        "view from above",
        "shot from above",
        "Jessica rabbit",
        "grabbed",
        "moob grab",
        "waist grab",
        "respectable",
        "Grab",
        "conceivable",
        "black fabric",
        "laying on belly",
        "medium stomach",
        "grab breasts",
        "round big belly",
        "from above",
        "above view",
        "navel",
        "sexy abdomen",
        "Chubby Belly",
        "arabian",
        "elizabeth",
        "absurdres",
        "blonde babe",
        "grab head",
        "tummy",
      ],
      hips: [
        "spaceship",
        "Ship",
        "very large hips",
        "space ship",
        "slim hips",
        "cock worship",
        "penis worship",
        "relationship",
        "medium hips",
        "round hips",
        "wide hip",
        "very wide hips",
        "ship",
        "hands on hips",
        "bondage ship",
        "hips grab",
        "chipmunking",
        "worship",
        "hip thrusts",
        "ass worship",
        "big hips",
        "narrow hips",
        "pirate ship",
        "penis workship",
        "grabbing hips",
        "small hip",
        "wide plump hips",
        "thicc hips",
        "large hips",
        "huge hips",
        "small hips",
        "hip bones",
        "ship deck",
        "wide hips",
        "hip",
        "hips",
        "gigantic hips",
        "super wide hips",
        "workship",
      ],
      back: [
        "on her back",
        "arched back",
        "lying on back",
        "on back",
        "background-room",
        "backpack",
        "back",
        "Farm background",
        "back_muscles",
        "bar background",
        "leaning back",
        "background",
        "backsack",
        "blue_background",
        "purple backpack",
        "look back",
        "Hunchback",
        "arching back",
        "cozy background",
        "red background",
        "reaching back",
        "looking back",
        "looking_back",
        "Background",
        "laying on back",
        "backlit",
        "barn background",
        "on_back",
        "back pov",
        "head back",
        "backwards",
        "men background",
        "dark background",
        "backboob",
        "void background",
        "backward",
        "On back",
        "backlighting",
        "background-sea",
        "muscular back",
        "back view",
        "grey background",
        "backfemale",
        "city background",
        "turn back",
        "back arched",
      ],
      waist: [
        "bent at waist",
        "waist",
        "microwaist",
        "stanched waist",
        "small waist",
        "lowwaisted",
        "slim waist",
        "tiny waist",
        "very slim waist",
        "thin waists",
        "love handles",
        "waist grab",
        "hands on waist",
        "slender waist",
        "thin waist",
        "highwaisted",
        "narrow waist",
        "waists",
        "from waist up",
      ],
    },
    other: {
      skin: [
        "oiled skin",
        "light blue skin",
        "soft skin",
        "green skin male",
        "blushing skin",
        "clean skin",
        "white pale skin",
        "white skin",
        "sweaty skin",
        "light skin",
        "standing doggy",
        "wrinkled skin",
        "stanched",
        "sultan",
        "kittan_bachika",
        "skinny body",
        "wet skin",
        "realistic skin",
        "marked foreskin",
        "tank",
        "skinny male",
        "Tanya",
        "fair skin",
        "green skin",
        "standing male",
        "shiny_skin",
        "shiny skin",
        "white-skin",
        "1futanari",
        "textured skin",
        "skinny thighs",
        "pink scaly skin",
        "skin pores",
        "mitanko",
        "Foreskin",
        "oily wet skin",
        "stanched waist",
        "puffy foreskin",
        "glossy skin",
        "dark grey skin",
        "impaled by cock",
        "fleshmutant",
        "skin textures",
        "sun tan marks",
        "dark skinned",
        "black skin man",
        "grey skin",
        "palette",
        "clear skin",
        "skin details",
        "distant",
        "a tanned girl",
        "standing split",
        "tan line",
        "dark-skinned",
        "skinhairdetail",
        "light-skinned",
        "yellow tank top",
        "dark skin",
        "lightskin",
        "pale woman",
        "pale skin",
        "skinny abdomen",
        "Green skin",
        "detailed skin",
        "tight tank top",
        "perfect skin",
        "SkinDetail",
        "Standing",
        "limited palette",
        "tanktop",
        "dark skin man",
        "skin",
        "brown skin",
        "standing males",
        "detailed_skins",
        "deepblue skin",
        "very dark skin",
        "skinned",
        "pale",
        "tank top",
        "skinny",
        "dark skin men",
        "oily skin",
        "light oily skin",
        "golden skin",
        "natural skin",
        "SkinHairDetail",
        "skinny girl",
        "shaded skin",
        "Trixie_tang",
        "black-skinned",
        "very pale skin",
        "tanned skin",
        "distance",
        "glowing skin",
        "white tanktop",
        "black skin",
        "skined",
        "standing",
        "skinsmug",
        "standing behind",
        "colored skin",
        "skin blushing",
        "red skin",
        "pale white skin",
        "tanned",
        "skin tight",
        "slimy skin",
        "gold on skin",
        "skindentation",
        "cybermutant",
        "skintight",
        "gray skin",
        "impaled",
        "foreskin",
        "pale white-skin",
        "white tank top",
        "standing alone",
        "dark skin male",
        "futanari",
        "stand",
        "tanline",
        "man standing",
        "very skinny",
        "skinindention",
        "1 futanari",
        "tan skin",
        "standing sex",
        "orange skin",
        "yellow skin",
        "Dark-Skinned",
        "skinny legs",
        "standing up",
        "blue skin",
        "deep skin",
        "tan",
        "tanlines",
        "tan lines",
      ],
      shoulders: [
        "broad shoulders",
        "free shoulders",
        "bare shoulders",
        "off shoulder",
        "shoulder",
        "off shoulders",
        "shoulder pads",
        "shoulder tattoo",
        "bare shoulder",
        "off-shoulder",
        "shoulders",
        "bare_shoulders",
        "wide shoulders",
      ],
      joints: [
        "knee-high socks",
        "knee-highs",
        "bound ankles",
        "kneeling facial",
        "doll joints",
        "kneeling slut",
        "buried knees",
        "robot joints",
        "gold anklets",
        "kneeling",
        "knees apart",
        "wrist",
        "wrists",
        "slim ankles",
        "on her knees",
        "on the knees",
        "knee boots",
        "knee",
        "thin ankles",
        "ankle",
        "knee-high",
        "elbows",
        "girl kneeling",
        "one knee up",
        "joints",
        "elbow gloves",
        "fat knees",
        "wrists bound",
        "thin ankle",
        "thin knees",
        "knee socks",
        "anklets",
        "knees",
        "knees up",
        "ankles",
        "on knees",
        "on elbows",
        "elbow",
        "kneeling female",
        "kneepits",
        "KNEE",
        "wrist cuffs",
        "knee up",
      ],
      neck: [
        "pearl necklace",
        "gold necklace",
        "fat neck",
        "necktie",
        "deepthroat sex",
        "neck",
        "hold neck",
        "collarbone",
        "throat bulge",
        "golden necklace",
        "deep in throat",
        "deepthroat",
        "deep throat",
        "anchor necklace",
        "throat grab",
        "kissing neck",
        "blue turtleneck",
        "purple necklace",
        "aqua necktie",
        "turtleneck",
        "neck bell",
        "kissing_neck",
        "heart necklace",
        "necklace",
        "throat",
      ],
    },
  },
  body_types: {
    age: {
      mature: [
        "Milf",
        "mature face",
        "milfs",
        "mature women",
        "athletic milf",
        "mature male",
        "Milf body",
        "veegilfl",
        "mature",
        "mature woman",
        "milf",
        "kawai milf",
        "sexy mature",
        "milfpeaches",
        "mature female",
      ],
      young: [
        "18 year old",
        "college girl",
        "young woman",
        "college",
        "young",
        "college student",
        "18 years old",
      ],
    },
    build: {
      curvy: [
        "thick",
        "chubby",
        "voluptuous body",
        "bbw",
        "curvy",
        "thick tongue",
        "very thick",
        "chubby balls",
        "thick body",
        "thick nipples",
        "thick calves",
        "thick white cum",
        "gigantic pawg",
        "Curvy",
        "thick lips",
        "thickset",
        "PAWG",
        "thick full lips",
        "Voluptuous body",
        "thick_thighs",
        "curvy shape",
        "thick arms",
        "voluptuous",
        "thick cock",
        "Thick",
        "Chubby",
        "thick woman",
        "thick dick",
        "thick_eyebrows",
        "curvy figure",
        "Voluptuous",
        "very thick lips",
        "thick cum",
        "thick thighs",
        "thick hair",
        "long thick hair",
        "chubby girl",
        "pawg",
        "thick tail",
        "thick eyebrows",
        "thick_tail",
        "thick eyerbrows",
        "thick_penis",
        "Thick thighs",
        "curvy body",
        "thick veins",
        "slightly chubby",
        "thick penis",
        "Chubby Belly",
        "thick legs",
        "chubby penis",
      ],
      muscular: [
        "absurd details",
        "sexy outfits",
        "fit legs",
        "muscular males",
        "athletic bosy",
        "cute outfit",
        "muscular thighs",
        "broad and abs",
        "muscular male",
        "athletic body",
        "fit body",
        "athletic",
        "muscular tits",
        "unbuttoned",
        "hyper muscular",
        "witch_outfit",
        "__outfit__",
        "absurd quality",
        "abstract",
        "muscular_anthro",
        "absurdly",
        "two-toned",
        "toned body",
        "skimpy outfits",
        "two-toned hair",
        "muscular figure",
        "abs",
        "maid outfit",
        "muscular man",
        "absurd",
        "graffiti",
        "muscular",
        "tight abs",
        "fat muscular",
        "toned female",
        "fit",
        "bondage outfit",
        "grabs",
        "office outfit",
        "ripped pants",
        "athletic milf",
        "impossible fit",
        "Jabstyle",
        "fit belly",
        "black outfit",
        "sexy outfit",
        "muscular_male",
        "ripped",
        "toned",
        "muscular back",
        "absurd res",
        "ripped clothes",
        "slim fit",
        "outfit",
        "outfits",
        "cock won't fit",
        "toned thighs",
        "absurdres",
      ],
      slim: [
        "soothing tones",
        "bathingtrunks",
        "breathing",
        "slender legs",
        "thin legs",
        "writhing around",
        "skimpy clothing",
        "skinny abdomen",
        "bathing in lake",
        "thin lips",
        "thin thighs",
        "white clothing",
        "heavy breathing",
        "tight clothing",
        "sheer clothing",
        "petite woman",
        "clothing aside",
        "thin waists",
        "petite ass",
        "thin ankles",
        "heavy_breathing",
        "shrug clothing",
        "slender",
        "writhing",
        "petite model",
        "slender face",
        "bathing",
        "skinny body",
        "very skinny",
        "slender waist",
        "petite body",
        "thin waist",
        "Slender girl",
        "braid petite",
        "busty petite",
        "Slender",
        "thin ankle",
        "thin knees",
        "under clothing",
        "skinny male",
        "petite breasts",
        "clothing",
        "thin",
        "slender body",
        "skinny girl",
        "skinny legs",
        "skinny thighs",
        "HDA_BathingXL",
        "thin body",
        "thin nose",
        "petite",
        "skinny",
        "slender hands",
        "soothing",
      ],
    },
    height: {
      short: [
        "feminine",
        "mini",
        "short_sleeves",
        "short legs",
        "tiny perky tits",
        "yoga short",
        "denim shorts",
        "orange shorts",
        "plaid shorts",
        "shorts wedgie",
        "tiny ass",
        "tiny nipples",
        "tiny dick",
        "short wavy hair",
        "tiny waist",
        "short bangs",
        "short shorts",
        "short penis",
        "shorts",
        "petite woman",
        "tiny body",
        "mini skirt",
        "petite ass",
        "miniskirt",
        "tiny smile",
        "shorter",
        "Tiny woman",
        "petite model",
        "black miniskirt",
        "booty shorts",
        "shorts down",
        "short hair",
        "green shorts",
        "feminine body",
        "pink short",
        "tiny",
        "petite body",
        "foreshortening",
        "miniwoman",
        "short height",
        "braid petite",
        "short male",
        "short",
        "tiny penis",
        "short skirt",
        "busty petite",
        "petite breasts",
        "tiny panties",
        "short red dress",
        "Tiny",
        "short Hair",
        "mini bikini",
        "short torso",
        "minimalistic",
        "shortstack",
        "shorter male",
        "short ponytail",
        "pleated shorts",
        "tiny cock",
        "mini skirt bra",
        "tiny man",
        "short girl",
        "jean shorts",
        "very short hair",
        "minijob",
        "petite",
        "short sleeves",
      ],
      tall: [
        "horizontally",
        "metallic",
        "bathroom stall",
        "extremely tall",
        "totally spies",
        "tall",
        "totally",
        "tall height",
        "stall",
      ],
    },
  },
  objects: {
    technology: {
      personal: [
        "smartwatch",
        "phone",
        "phone screen",
        "phone exposure",
        "close camera",
        "headphones",
        "facing camera",
        "candid camera",
        "phone pov",
        "camera",
      ],
      other: [
        "robot joints",
        "robot body",
        "robot girl",
        "robot",
        "android 18",
        "computers",
        "cyborg girl",
        "android",
        "robot eyes",
        "cyborg",
      ],
    },
    sex_toys: {
      insertable: [
        "dildo",
        "dildos",
        "dildo sex",
        "equine_dildo",
        "horse dildo",
        "vibrator",
        "multiple dildos",
        "riding dildo",
        "dildoes",
        "spiked dildo",
        "riding a dildo",
        "big dildo",
        "dildo in pussy",
        "grabbing dildo",
        "floating dildo",
        "huge dildo",
        "magic dildo",
        "dildo riding",
        "glowing dildo",
        "holding dildo",
      ],
      other: [
        "engaged",
        "bdsm rope",
        "breast bondage",
        "blindfolded",
        "ropes of cum",
        "leash",
        "Tape Bondage",
        "unworn gag",
        "leashed",
        "on a leash",
        "fur collar",
        "collared shirt",
        "ball gag",
        "detached collar",
        "unleashed",
        "luggage",
        "collared",
        "bondage",
        "collarbone",
        "red rope",
        "grope",
        "nude bondage",
        "Europe",
        "rope bondage",
        "collar",
        "duct tape gag",
        "tape gag",
        "leather bondage",
        "bondage ship",
        "spiked collar",
        "1 european girl",
        "ring gag",
        "green collar",
        "gold collar",
        "bondage outfit",
        "sailor_collar",
        "red ball gag",
        "wiffle gag",
        "blindfold",
        "dog collar",
        "handcuffs",
        "snake_bondage",
        "groped",
        "big ring gag",
        "being groped",
        "detached_collar",
        "rope",
        "tape bondage",
        "black collar",
        "Bondage",
        "blue collar",
        "european",
        "european 1girl",
        "collars",
        "leash pull",
        "linked collars",
        "sailor collar",
        "clv_gag",
        "ropes",
        "harnessgag",
        "gagged",
        "gag",
      ],
    },
    furniture: {
      seating: [
        "chair",
        "bite bedsheet",
        "on the bed",
        "beds",
        "male on sofa",
        "bed",
        "edge of bed",
        "bedroom eyes",
        "lying on bed",
        "bed room",
        "on a bed",
        "laying on bench",
        "in bed",
        "lying on a bed",
        "palace bedroom",
        "Lying on bed",
        "on a fur bed",
        "on_bed",
        "sex toys on bed",
        "inside bedroom",
        "grabbed",
        "obedient",
        "bedsheet",
        "laying on bed",
        "grabbed hair",
        "bedsheets",
        "bed sheet",
        "embedding",
        "sofa",
        "gamer bedroom",
        "pool chairs",
        "fucked in bed",
        "throne room",
        "in front of bed",
        "armchair",
        "bench",
        "obedient slut",
        "couch",
        "laying on a bed",
        "sit on a couch",
        "Bedroom",
        "stool",
        "white sofa",
        "on bed",
        "bedroom",
        "chairs",
        "cum_on_bed",
        "bunk beds",
        "throne",
        "royal bedroom",
        "lying in bed",
      ],
      other: [
        "Table",
        "Sex on Table",
        "respectable",
        "on desk",
        "desk",
        "bent over table",
        "hands on table",
        "sitting on desk",
        "Unforgettable",
        "table",
        "book shelf",
        "uncomfortable",
        "shelf",
      ],
    },
  },
  number_of_people: {
    couple: {
      mixed: ["futa with girl", "futa on girl", "futa fucks girl"],
      homosexual: [
        "gay",
        "2girls",
        "gay bukkake",
        "lesbian sex",
        "sexy 2girls",
        "2boys",
        "lesbians",
        "Gay",
        "lesbian",
        "yaoi",
        "Gay man",
        "2girls 1boy",
        "lesbian couple",
        "yuri",
        "2girls1boy",
      ],
      heterosexual: [
        "heterosexual",
        "hetero",
        "BREAK hetero",
        "1girl1boy",
        "heterochromia",
        "straightened",
        "straight hair",
        "hair straight",
        "straight",
        "straight-on",
      ],
    },
    single: {
      other: [
        "BREAK 1futa",
        "1futa",
        "1futanari",
        "1 futanari",
        "futanari",
        "androgynous",
      ],
      male: [
        "1boy 1girl",
        "s 1boy",
        "1girl1boy",
        "1BOY",
        "1man",
        "1boys",
        "2girls 1boy",
        "male focus",
        "female focus",
        "2girls1boy",
        "1Man",
        "1man behind",
        "1boy",
      ],
      female: [
        "1girls",
        "1boy 1girl",
        "exquisite 1girl",
        "1girl1boy",
        "european 1girl",
        "crying solo",
        "sexy 1girls",
        "solo",
        "solo girl",
        "Solo",
        "female focus",
        "BREAK solo",
        "BREAK 1girl",
        "1girl",
        "1guy1girl",
        "Goth girl 1girl",
        "solo focus",
        "1girl only",
      ],
    },
    group: {
      small: [
        "FFM sex scene",
        "mmf threesome",
        "3girls",
        "threesome",
        "ffm",
        "mmf",
        "MMF threesome",
        "Threesome sex",
        "FFM",
        "mmm_threesome",
        "2girls 1boy",
        "ffm threesome",
        "2girls1boy",
        "3boys",
        "MMF",
        "threesome sex",
        "Threesome",
        "3girl",
      ],
      large: [
        "multiple views",
        "bukkake",
        "multiple view",
        "multiple images",
        "multiple males",
        "multiple dildos",
        "multiple boys",
        "harem girls",
        "multiple girls",
        "gangbang sex",
        "MULTIPLE",
        "gangbanged",
        "gangbang",
        "multiple darfs",
        "blowbang",
        "arabian harem",
        "harem",
        "orgy",
        "multiple lamps",
        "bwc gangbang",
        "multiple_boys",
        "multiple men",
        "multiples",
        "group sex",
        "gay bukkake",
        "bbc gangbang",
        "multiple",
        "goblin gangbang",
        "multiple cocks",
        "MULTIPLE BOYS",
      ],
    },
  },
  sexual_actions: {
    foreplay: {
      oral: [
        "sucking finger",
        "licking feet",
        "pec sucking",
        "licking cock",
        "licking breast",
        "Kissing",
        "breast sucking",
        "licking penis",
        "licking nipple",
        "kissing body",
        "french kissing",
        "nipple sucking",
        "licking",
        "sucking",
        "ball sucking",
        "kissing neck",
        "licking dick",
        "women kissing",
        "cock licking",
        "sucking balls",
        "licking ass",
        "kissing",
        "licking lips",
        "sucking nipple",
        "kissing penis",
        "licking balls",
        "licking the tip",
        "licking pussy",
        "sucking cock",
        "sucking breasts",
        "kissing_neck",
        "slave sucking",
        "kissing male",
        "breastsucking",
        "self sucking",
      ],
      manual: [
        "rubbing vagina",
        "jerking",
        "masturbation",
        "double handjob",
        "anal fingering",
        "stroking",
        "handjob behind",
        "fingering pussy",
        "stroking cock",
        "fingering",
        "POV_handjob",
        "FINGERING",
        "handjob",
        "rubbing",
        "giving_handjob",
        "masturbate",
        "stroking penis",
      ],
      other: [
        "groping pussy",
        "ass grabbing",
        "ass grab",
        "groping her",
        "tongue teasing",
        "breast grab",
        "groping breast",
        "teasing cock",
        "groping",
        "teasing viewer",
        "teasing",
        "teasing look",
      ],
    },
    climax: {
      female: [
        "orgasm shaking",
        "ahegao face",
        "ahegao",
        "orgasm",
        "Ahegao",
        "male orgasms",
        "female orgasm",
        "Orgasm",
        "intense orgasm",
        "male orgasm",
        "huge squirting",
        "orgasm face",
        "ruined orgasm",
        "Scream orgasm",
        "squirting",
        "imminent orgasm",
        "orgasm torture",
        "orgasmic",
        "orgasms",
        "orgasmic face",
        "o-face",
      ],
      male: [
        "cumshotruined",
        "cum on ass",
        "pearl necklace",
        "cum on boy",
        "cum on hand",
        "cum on chin",
        "cum on legs",
        "cum in face",
        "huge cumshot",
        "kneeling facial",
        "cum on face",
        "cum inside",
        "cum on body",
        "cumshots",
        "cum on penis",
        "cumshot",
        "massive cumshot",
        "facial hair",
        "massive facial",
        "cum in uterus",
        "cum on boobs",
        "cum in anus",
        "ejaculation",
        "cuminmouthXL",
        "cum on thigh",
        "cum on stomach",
        "cum in hair",
        "cum on pussy",
        "cum on breasts",
        "large cumshot",
        "cum on gloves",
        "messy creampie",
        "facial freckles",
        "creampiet",
        "creampie",
        "facial mark",
        "huge-cumshot",
        "cum in pussy",
        "cum in nose",
        "cum on tits",
        "cum in armpits",
        "anal creampie",
        "cum in ass",
        "cum on tongue",
        "cum on chest",
        "man ejaculation",
        "cum in mouth",
        "creampied",
        "cum on mouth",
        "cum on balls",
        "facial",
        "cum on hair",
        "cum on head",
        "facial cumshot",
        "cum on her body",
        "cum on belly",
      ],
      multiple: [
        "gay bukkake",
        "bukkake",
        "cum bath",
        "cumbath",
        "excessive cum",
        "cum covered",
      ],
    },
    penetration: {
      oral: [
        "fellatio",
        "2 women blowjob",
        "face fuck",
        "facefuck",
        "triple blowjob",
        "blowjob",
        "Blowjob POV",
        "irrumatio",
        "Blowjob",
        "deepthroat",
        "after fellatio",
        "deepthroat sex",
        "cunnilingus",
        "double blowjob",
        "bbc blowjob",
        "double fellatio",
      ],
      vaginal: [
        "pov missionary",
        "cowgirl pose",
        "reverse cowgirl",
        "doggy style sex",
        "cowgirl",
        "doggystyle",
        "missionary",
        "doggystyle sex",
        "doggystylel sex",
        "doggystylel",
        "vaginal sex",
        "cowgirl sex",
        "missionary sex",
        "doggy style",
      ],
      anal: [
        "godpussy1",
        "padparadscha",
        "headphones",
        "headpiece",
        "anal sex",
        "assfuck",
        "headpat",
      ],
    },
  },
  specific_characters: {
    game: {
      specific: [
        "princess zelda",
        "princess peach",
        "zelda",
        "Lara Croft",
        "samus",
        "girl lara croft",
        "link",
        "2b",
        "tifa lockheart",
        "Mario and Luigi",
        "Zelda",
        "tifa lockhart",
        "Mario",
        "tifa",
        "tifa_lockhart",
        "superMario",
        "ZeldaSDXL",
        "Lara croft",
        "Princess Peach",
        "Princess Zelda",
        "linked collars",
        "linked",
        "2boys",
      ],
    },
    other: {
      disney: [
        "Anna frozen",
        "rapunzel",
        "jasmine",
        "ElsaXPL",
        "Elsa",
        "moana",
        "Rapunzel",
        "belle",
        "anna and elsa",
        "sweetie belle",
        "Belle",
        "elsa",
        "Ariel",
        "elsa hair",
        "Johanna",
        "Jasmine",
        "Anna hair",
        "ArielWaifu",
        "ariel",
        "Anna",
        "disney princess",
        "anna",
        "RapunzelWaifu",
      ],
      comic: ["wonder woman", "spider-gwen", "Spider-Gwen"],
    },
    anime: {
      specific: [
        "dynamic",
        "marimakinami",
        "Dynamic angle",
        "dynamic view",
        "mari makinami",
        "asuka langley",
        "rei ayanami",
        "mikuhatsune",
        "dynamics",
        "asuka",
        "ayanami",
        "rei",
        "miku hatsune",
        "hinata hyuuga",
        "heart dynamics",
        "dynamic pov",
        "Dynamic",
        "dynamic angle",
        "hatsune miku",
        "hinata",
        "ayanami_rei",
        "Sailor Moon",
        "miku",
        "reinhardt",
        "dynamic pose",
        "makinami",
        "nami",
      ],
      general: ["waifu", "RapunzelWaifu", "ArielWaifu"],
    },
  },
  image_quality: {
    lighting: {
      bright: [
        "Brightly",
        "backlit",
        "bright sunlight",
        "bright eyes",
        "Brightly Lit",
        "bright",
        "bright-lit",
        "bright day",
        "sunlight",
        "well-lit",
        "bright lighting",
        "golden hour",
        "bright colors",
        "studio lighting",
        "bright-lit room",
        "bright light",
      ],
      dark: [
        "dim lighting",
        "dark green gown",
        "dark night",
        "very low light",
        "dark blue hair",
        "dark room",
        "nightgown",
        "nightclub",
        "very dark dick",
        "late night",
        "dark lighting",
        "dark eyeliner",
        "dark blue eyes",
        "night",
        "night sky",
        "lowlight",
        "dark ambience",
        "dark brown eyes",
        "shadows",
        "dark pupils",
        "dark penis",
        "dark grey skin",
        "dark alley",
        "dark grey eyes",
        "dark hair",
        "dimly lit",
        "dark skinned",
        "Low light",
        "dark sky",
        "dark roots",
        "dark background",
        "dark light",
        "dim light",
        "dark alleyway",
        "dark studio",
        "dark eyeshadow",
        "dark-skinned",
        "dimples",
        "Dark",
        "dark elf",
        "dark skin",
        "dimly",
        "Cold Night",
        "dim",
        "dark forest",
        "deep shadows",
        "dimmed",
        "Night",
        "dark theme",
        "dark",
        "in the dark",
        "dark shadows",
        "dark skin man",
        "moody lighting",
        "very dark skin",
        "by night",
        "perfect shadows",
        "chiaroscuro",
        "dark makeup",
        "dark skin men",
        "moody",
        "rainy night",
        "at night",
        "low light",
        "darkness",
        "nighttime",
        "dark lipstick",
        "nightdress",
        "dark skin male",
        "dark brown hair",
        "night time",
        "dimmed lights",
        "gentle shadows",
        "dark eyes",
        "night club",
        "Dark-Skinned",
        "man in the dark",
      ],
    },
    style: {
      realistic: [
        "very detailed",
        "semi realistic",
        "hyper-detailed",
        "realistic pussy",
        "hyperdetailed",
        "detailed penis",
        "photorealistic",
        "realistic fur",
        "Realistic style",
        "detailed art",
        "detailed hands",
        "detailed skin",
        "detailed fur",
        "detailed eyes",
        "realistic photo",
        "detailed lips",
        "detailed photo",
        "highly detailed",
        "ultra realistic",
        "detailed",
        "detailed cock",
        "Detailed",
        "realistic eyes",
        "hyper-realistic",
        "realistic girl",
        "realistic",
        "detailed_skins",
        "detailed image",
        "semi-realistic",
        "Realistic",
        "detailed irises",
        "high detailed",
        "Ultra realistic",
        "A realistic",
        "photo-realistic",
        "realistic skin",
        "detailed body",
        "detailed pussy",
        "detailed face",
        "hyperrealistic",
        "Photorealistic",
        "detailed hand",
        "detailed scales",
        "super detailed",
        "realistic face",
        "ultra-detailed",
        "high-detailed",
        "ultradetailed",
        "ultra detailed",
        "realistic style",
        "rich detailed",
        "detailed balls",
        "live realistic",
      ],
      artistic: [
        "painted",
        "anime artwork",
        "cartoon",
        "painted nails",
        "_anime",
        "Painted",
        "Anime",
        "digital art",
        "anime screencap",
        "anime coloring",
        "anime",
        "source anime",
        "anime style",
        "AnimeA",
        "source_anime",
        "illustration",
        "cute anime face",
        "source_cartoon",
        "source _anime",
        "western cartoon",
      ],
    },
    resolution: {
      high: [
        "8k detail",
        "high definition",
        "ultra high res",
        "8k raw photo",
        "4k",
        "8K resolution",
        "4k quality",
        "uhd",
        "HDA_ZoeyXL",
        "8k",
        "hd masterpeice",
        "high res image",
        "high res",
        "hd",
        "8k resolution",
        "HD quality",
        "8K",
        "HD",
        "HD32K",
        "HDA_NovaXL",
        "fgrhd",
        "UHD",
        "8k UHD",
        "highres",
        "HDA_BathingXL",
        "4k uhd",
        "highres image",
        "high resolution",
      ],
      low: ["low resolution", "low quality"],
    },
  },
  fetishes: {
    body_modification: {
      tattoos: [
        "tattooed arms",
        "glowing tattoos",
        "slut_tattoo",
        "tattoo body",
        "tattoos",
        "womb tattoo",
        "breast tattoos",
        "blue tattoos",
        "tattoo-large",
        "no tattoos",
        "shoulder tattoo",
        "arm tattoos",
        "arms tattooed",
        "tattooed",
        "tribal tattoos",
        "tattoo",
        "face tattoos",
      ],
      piercings: [
        "face piercing",
        "piercing",
        "pussy piercing",
        "navel piercing",
        "nipple piercing",
        "nose piercings",
        "ear piercings",
        "corset_piercing",
        "pierced nipples",
        "piercings",
      ],
    },
    bdsm: {
      domination: [
        "masterpiece",
        "male domination",
        "collared",
        "hd masterpeice",
        "submission",
        "domination",
        "masterpeice",
        "a masterpiece",
        "collared shirt",
        "slave sucking",
        "slave pussy",
        "slave",
        "Masterpiece",
      ],
      bondage: [
        "bdsm rope",
        "breast bondage",
        "tied up",
        "ropes of cum",
        "Tape Bondage",
        "bondage",
        "red rope",
        "grope",
        "nude bondage",
        "Europe",
        "rope bondage",
        "leather bondage",
        "bondage ship",
        "1 european girl",
        "bondage outfit",
        "snake_bondage",
        "groped",
        "chains",
        "being groped",
        "rope",
        "tape bondage",
        "shibari",
        "Bondage",
        "european",
        "european 1girl",
        "painful shibari",
        "ropes",
      ],
    },
    clothing: {
      uniform: [
        "maid uniform",
        "teacher",
        "police uniform",
        "small maid hat",
        "military hat",
        "maid",
        "mermaid",
        "Teacher",
        "maid hat",
        "maid dress",
        "maid outfit",
        "police",
        "military",
        "nurse",
      ],
      transformation: [
        "batgirl mask",
        "shotgun",
        "nightgown",
        "batgirl",
        "ttgl",
        "ratgirl",
        "mtf",
      ],
    },
  },
  setting: {
    indoor: {
      home: [
        "glass shower",
        "bathroom",
        "bedroom eyes",
        "showering",
        "palace bedroom",
        "inside bedroom",
        "school bathroom",
        "kitchen",
        "shower",
        "bathroom stall",
        "bathtub",
        "gamer bedroom",
        "couch",
        "living room",
        "Bedroom",
        "sit on a couch",
        "in a kitchen",
        "bedroom",
        "royal bedroom",
      ],
      public: [
        "bare",
        "office boy",
        "hotel room",
        "bare navel",
        "bare shoulders",
        "bare shoulder",
        "women bare feet",
        "oozora_subaru_",
        "bar background",
        "Baroque",
        "in classroom",
        "gym",
        "BREAK barn",
        "library",
        "club",
        "office man",
        "school",
        "bare arms",
        "nobara kugisaki",
        "hospital",
        "barren",
        "nightclub",
        "restaurant",
        "sexy gym girl",
        "club setting",
        "barely",
        "barn",
        "bare midriff",
        "Barbie",
        "bar",
        "school bathroom",
        "in a gym",
        "hotel",
        "barefoot",
        "barn background",
        "office outfit",
        "embarrassed",
        "bare ass",
        "classroom",
        "bare feet",
        "office dress",
        "in the office",
        "embarassed",
        "office girl",
        "hospital room",
        "bare tits",
        "library stacks",
        "barrel",
        "in hotel room",
        "office",
        "maebari",
        "bara",
        "shibari",
        "school uniform",
        "hotel exterior",
        "bare chest",
        "office lady",
        "night club",
        "strip club",
        "nobara",
        "gymnast",
        "in office",
        "painful shibari",
        "Barbie doll",
        "embarrased",
        "school_uniform",
        "bare_shoulders",
        "office room",
        "barbara",
      ],
    },
    outdoor: {
      urban: [
        "restrained",
        "New York City",
        "male restrained",
        "parking",
        "Restrained",
        "skyscraper",
        "city",
        "alleyway",
        "dark alley",
        "water sparkles",
        "train",
        "City",
        "subway",
        "streets",
        "street fighter",
        "park",
        "crowded train",
        "trained",
        "sparkling",
        "crowded street",
        "trained thighs",
        "street",
        "sparkles",
        "sparkle",
        "dark alleyway",
        "alley",
        "city background",
        "public park",
        "on the street",
      ],
      nature: [
        "airfield",
        "in jungle",
        "mountains",
        "caulfield",
        "on the beach",
        "dark forest",
        "bathing in lake",
        "depth_of_field",
        "outdoor garden",
        "Ocean",
        "piledriver pose",
        "daphne_blake",
        "at the beach",
        "lake",
        "waterfall",
        "field",
        "ocean",
        "Brazil jungle",
        "forest",
        "in the river",
        "fantasy forest",
        "depth of field",
        "royal gardens",
        "Daphne Blake",
        "jungle",
        "Blake",
        "crowded beach",
        "in a garden",
        "piledriver",
        "pine forest",
        "beach",
        "mountain",
        "lying on beach",
        "daphney blake",
        "river",
        "is daphne blake",
        "blake",
        "Max caulfield",
        "daphne blake",
        "battlefield",
        "girl in jungle",
        "gardens",
        "sunny in forest",
        "at the river",
        "on beach",
        "garden",
      ],
    },
    fantasy: {
      medieval: [
        "dungeon",
        "tavern setting",
        "medieval tavern",
        "castle exterior",
        "medieval prison",
        "throne room",
        "medieval theme",
        "medieval",
        "tavern",
        "medieval dress",
        "castle",
      ],
      futuristic: ["cyberpunk", "spaceship"],
    },
  },
};
function generateSexyPrompt(
  possibilityBodyDesc = 0.7,
  possibilityClothing = 0.9,
  possibilitySetting = 0.3,
  possibilityExtras = 0.2,
  possibilityImageQuality = 0.5,
  possibilityPenetration = 0.8,
  possibilityCharacter = 0.3
) {
  function randomPick(array, n = 1) {
    if (n === 1) return array[Math.floor(Math.random() * array.length)];
    return Array.from(
      { length: n },
      () => array[Math.floor(Math.random() * array.length)]
    );
  }

  function pickFromThirdLevel(obj) {
    let current = obj;
    let path = [];

    while (!Array.isArray(current)) {
      const keys = Object.keys(current);
      const randomKey = randomPick(keys);
      path.push(randomKey);
      current = current[randomKey];

      // Safety check in case the structure is not as expected
      if (typeof current !== "object" || current === null) {
        return null;
      }
    }

    // At this point, current should be an array
    const randomValue = randomPick(current);
    //return `${path.join(' ')} ${randomValue}`;
    return randomValue;
  }

  function generateRoleCount() {
    const options = [
      "1girl,solo",
      "1girl,1boy",
      "2girl",
      "threesome,1girl,2boy",
      "threesome,2girl,1boy",
      "threesome,3girl",
      "group",
    ];
    return randomPick(options);
  }

  function generateShortDescription(roleCount) {
    const penetrationActions =
      Math.random() < possibilityPenetration
        ? Object.values(classifier.sexual_actions.penetration).flat()
        : [];
    const foreplayActions = Object.values(
      classifier.sexual_actions.foreplay
    ).flat();
    const climaxActions = Object.values(
      classifier.sexual_actions.climax
    ).flat();

    let description = "";
    if (roleCount === "1girl,solo") {
      description = `a girl`;
    } else if (roleCount === "2girl") {
      description = `two girls`;
    } else if (roleCount === "1girl,1boy") {
      description = `a girl with a man`;
    } else if (roleCount === "group") {
      const groupSize = randomPick(
        Object.keys(classifier.number_of_people.group)
      );
      description = `a ${groupSize} group`;
    } else {
      description = roleCount;
    }

    if (penetrationActions.length)
      description += ` ${randomPick(penetrationActions)}`;
    description += `, ${randomPick(foreplayActions)}, ${randomPick(
      climaxActions
    )}`;

    return description;
  }

  function generateBodyDescription() {
    return Array.from({ length: Math.floor(Math.random() * 3) + 1 }, () => {
    terms = []
      for (key in classifier.body_parts) {
        if (Math.random() < possibilityBodyDesc) {
            terms.push(  pickFromThirdLevel(classifier.body_parts[key]));
        }
      }
      return terms;
    }).filter(Boolean);
  }

  function generateClothing() {
    return Array.from({ length: Math.floor(Math.random() * 3) + 1 }, () => {
        terms = []
      for (key in classifier.clothing) {
        //if (key === 'tall' || key === 'short') continue;
        if (Math.random() < possibilityClothing) {
          terms.push( pickFromThirdLevel(classifier.clothing[key]));
        }
      }
      return terms;
    }).filter(Boolean);
  }

  function generateSetting() {
    let terms = []
    for (key in classifier.setting) {
      if (Math.random() < possibilitySetting) {
        terms.push(pickFromThirdLevel(classifier.setting[key]));
      }
    }
    return terms.join(", ");
  }

  function generateExtras() {
    return Array.from({ length: Math.floor(Math.random() * 2) + 1 }, () => {
      if (Math.random() < possibilityExtras) {
        const category = randomPick(["objects", "fetishes"]);
        return pickFromThirdLevel(classifier[category]);
      }
    }).filter(Boolean);
  }

  function generateImageQuality() {
    if (Math.random() < possibilityImageQuality) {
      const style = pickFromThirdLevel(classifier.image_quality.style);
      const lighting = pickFromThirdLevel(classifier.image_quality.lighting);
      return `${style}, ${lighting}`;
    }
    return "";
  }

  function generateCharacter() {
    let terms = []
    for (key in classifier.specific_characters) {
      if (Math.random() < possibilityCharacter) {
        terms.push(pickFromThirdLevel(classifier.specific_characters[key]));
      }
    }
    return terms.join(", ");
  }

  const roleCount = generateRoleCount();
  const shortDescription = generateShortDescription(roleCount);
  const bodyDescription = generateBodyDescription();
  const clothing = generateClothing();
  const setting = generateSetting();
  const extras = generateExtras();
  const imageQuality = generateImageQuality();
  const character = generateCharacter();

  const promptParts = [
    roleCount,
    shortDescription,
    ...bodyDescription,
    ...clothing,
    setting,
    ...extras,
    imageQuality,
    character,
  ].filter(Boolean);

  return promptParts.join(", ");
}

// Usage example:
// const prompt = generateImagePrompt(classifier);
// console.log(prompt);
// Usage example:
